name: "QAS Deployment"

on:
    push:
        branches:
            - main

jobs:
    deploy:
        uses: ./.github/workflows/jsonrest_deploy_base.yaml
        with:
            working-directory: .
            stack-name: "integration-stack"
            environment: "qas"
            aws-region: "ap-southeast-2"
            client-name: "ology"
            integration-name: "integration"
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_QAS }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_QAS }}
            CLIENT_API_KEY: ${{ secrets.CONFLAB_STRIPESECRETKEY_QAS }}
